### ISSUE TITLE
我用docker compose搭了后，重启容器后数据不见了，是哪里有问题吗？

### ISSUE THREAD

**Issue by winsphinx** [javahuang/SurveyKing#42]
我的compose.yml如下：
``` yaml
version: '3'
services:
  surveyking:
    image: surveyking/surveyking
    container_name: surveyking
    restart: unless-stopped
    environment:
      #- PUID=1000
      #- PGID=1000
    volumes:
      - ./files:/surveyking/files
      - ./logs:/surveyking/logs
    ports:
      - 1991:1991
```
我从docker内部查到就是这两个卷，还要涉及其他的吗？
